services:
  henchman:
    build: .
    ports:
      - "9090:9090"
    expose:
      - "6474"
    environment:
      HENCH_PORT: "6474"
      HENCH_METRICS_PORT: "9090"
      HENCH_MAX_MEMORY: "536870912"
    restart: unless-stopped
